// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package deleter

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"sync"
)

// Ensure, that S3DeleterMock does implement S3Deleter.
// If this is not the case, regenerate this file with moq.
var _ S3Deleter = &S3DeleterMock{}

// S3DeleterMock is a mock implementation of S3Deleter.
//
//	func TestSomethingThatUsesS3Deleter(t *testing.T) {
//
//		// make and configure a mocked S3Deleter
//		mockedS3Deleter := &S3DeleterMock{
//			DeleteObjectsFunc: func(ctx context.Context, params *s3.DeleteObjectsInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error) {
//				panic("mock out the DeleteObjects method")
//			},
//		}
//
//		// use mockedS3Deleter in code that requires S3Deleter
//		// and then make assertions.
//
//	}
type S3DeleterMock struct {
	// DeleteObjectsFunc mocks the DeleteObjects method.
	DeleteObjectsFunc func(ctx context.Context, params *s3.DeleteObjectsInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteObjects holds details about calls to the DeleteObjects method.
		DeleteObjects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *s3.DeleteObjectsInput
			// OptFns is the optFns argument value.
			OptFns []func(*s3.Options)
		}
	}
	lockDeleteObjects sync.RWMutex
}

// DeleteObjects calls DeleteObjectsFunc.
func (mock *S3DeleterMock) DeleteObjects(ctx context.Context, params *s3.DeleteObjectsInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error) {
	if mock.DeleteObjectsFunc == nil {
		panic("S3DeleterMock.DeleteObjectsFunc: method is nil but S3Deleter.DeleteObjects was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *s3.DeleteObjectsInput
		OptFns []func(*s3.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockDeleteObjects.Lock()
	mock.calls.DeleteObjects = append(mock.calls.DeleteObjects, callInfo)
	mock.lockDeleteObjects.Unlock()
	return mock.DeleteObjectsFunc(ctx, params, optFns...)
}

// DeleteObjectsCalls gets all the calls that were made to DeleteObjects.
// Check the length with:
//
//	len(mockedS3Deleter.DeleteObjectsCalls())
func (mock *S3DeleterMock) DeleteObjectsCalls() []struct {
	Ctx    context.Context
	Params *s3.DeleteObjectsInput
	OptFns []func(*s3.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *s3.DeleteObjectsInput
		OptFns []func(*s3.Options)
	}
	mock.lockDeleteObjects.RLock()
	calls = mock.calls.DeleteObjects
	mock.lockDeleteObjects.RUnlock()
	return calls
}
