// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package engine

import (
	"github.com/balli/aws-s3-gda-cleaner/internal/deleter"
	"github.com/balli/aws-s3-gda-cleaner/internal/notifier"
	"github.com/balli/aws-s3-gda-cleaner/internal/scanner"
	"sync"
)

// Ensure, that NotifierMock does implement notifier.Notifier.
// If this is not the case, regenerate this file with moq.
var _ notifier.Notifier = &NotifierMock{}

// NotifierMock is a mock implementation of notifier.Notifier.
//
//	func TestSomethingThatUsesNotifier(t *testing.T) {
//
//		// make and configure a mocked notifier.Notifier
//		mockedNotifier := &NotifierMock{
//			SendDeletionReportFunc: func(candidates []scanner.S3Object, result *deleter.DeletionResult) error {
//				panic("mock out the SendDeletionReport method")
//			},
//			SendDeletionSummaryFunc: func(candidates []scanner.S3Object, approvalURL string) error {
//				panic("mock out the SendDeletionSummary method")
//			},
//		}
//
//		// use mockedNotifier in code that requires notifier.Notifier
//		// and then make assertions.
//
//	}
type NotifierMock struct {
	// SendDeletionReportFunc mocks the SendDeletionReport method.
	SendDeletionReportFunc func(candidates []scanner.S3Object, result *deleter.DeletionResult) error

	// SendDeletionSummaryFunc mocks the SendDeletionSummary method.
	SendDeletionSummaryFunc func(candidates []scanner.S3Object, approvalURL string) error

	// calls tracks calls to the methods.
	calls struct {
		// SendDeletionReport holds details about calls to the SendDeletionReport method.
		SendDeletionReport []struct {
			// Candidates is the candidates argument value.
			Candidates []scanner.S3Object
			// Result is the result argument value.
			Result *deleter.DeletionResult
		}
		// SendDeletionSummary holds details about calls to the SendDeletionSummary method.
		SendDeletionSummary []struct {
			// Candidates is the candidates argument value.
			Candidates []scanner.S3Object
			// ApprovalURL is the approvalURL argument value.
			ApprovalURL string
		}
	}
	lockSendDeletionReport  sync.RWMutex
	lockSendDeletionSummary sync.RWMutex
}

// SendDeletionReport calls SendDeletionReportFunc.
func (mock *NotifierMock) SendDeletionReport(candidates []scanner.S3Object, result *deleter.DeletionResult) error {
	if mock.SendDeletionReportFunc == nil {
		panic("NotifierMock.SendDeletionReportFunc: method is nil but Notifier.SendDeletionReport was just called")
	}
	callInfo := struct {
		Candidates []scanner.S3Object
		Result     *deleter.DeletionResult
	}{
		Candidates: candidates,
		Result:     result,
	}
	mock.lockSendDeletionReport.Lock()
	mock.calls.SendDeletionReport = append(mock.calls.SendDeletionReport, callInfo)
	mock.lockSendDeletionReport.Unlock()
	return mock.SendDeletionReportFunc(candidates, result)
}

// SendDeletionReportCalls gets all the calls that were made to SendDeletionReport.
// Check the length with:
//
//	len(mockedNotifier.SendDeletionReportCalls())
func (mock *NotifierMock) SendDeletionReportCalls() []struct {
	Candidates []scanner.S3Object
	Result     *deleter.DeletionResult
} {
	var calls []struct {
		Candidates []scanner.S3Object
		Result     *deleter.DeletionResult
	}
	mock.lockSendDeletionReport.RLock()
	calls = mock.calls.SendDeletionReport
	mock.lockSendDeletionReport.RUnlock()
	return calls
}

// SendDeletionSummary calls SendDeletionSummaryFunc.
func (mock *NotifierMock) SendDeletionSummary(candidates []scanner.S3Object, approvalURL string) error {
	if mock.SendDeletionSummaryFunc == nil {
		panic("NotifierMock.SendDeletionSummaryFunc: method is nil but Notifier.SendDeletionSummary was just called")
	}
	callInfo := struct {
		Candidates  []scanner.S3Object
		ApprovalURL string
	}{
		Candidates:  candidates,
		ApprovalURL: approvalURL,
	}
	mock.lockSendDeletionSummary.Lock()
	mock.calls.SendDeletionSummary = append(mock.calls.SendDeletionSummary, callInfo)
	mock.lockSendDeletionSummary.Unlock()
	return mock.SendDeletionSummaryFunc(candidates, approvalURL)
}

// SendDeletionSummaryCalls gets all the calls that were made to SendDeletionSummary.
// Check the length with:
//
//	len(mockedNotifier.SendDeletionSummaryCalls())
func (mock *NotifierMock) SendDeletionSummaryCalls() []struct {
	Candidates  []scanner.S3Object
	ApprovalURL string
} {
	var calls []struct {
		Candidates  []scanner.S3Object
		ApprovalURL string
	}
	mock.lockSendDeletionSummary.RLock()
	calls = mock.calls.SendDeletionSummary
	mock.lockSendDeletionSummary.RUnlock()
	return calls
}
