// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package engine

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/balli/aws-s3-gda-cleaner/internal/scanner"
	"sync"
)

// Ensure, that S3ClientMock does implement scanner.S3Client.
// If this is not the case, regenerate this file with moq.
var _ scanner.S3Client = &S3ClientMock{}

// S3ClientMock is a mock implementation of scanner.S3Client.
//
//	func TestSomethingThatUsesS3Client(t *testing.T) {
//
//		// make and configure a mocked scanner.S3Client
//		mockedS3Client := &S3ClientMock{
//			ListObjectsV2Func: func(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error) {
//				panic("mock out the ListObjectsV2 method")
//			},
//		}
//
//		// use mockedS3Client in code that requires scanner.S3Client
//		// and then make assertions.
//
//	}
type S3ClientMock struct {
	// ListObjectsV2Func mocks the ListObjectsV2 method.
	ListObjectsV2Func func(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListObjectsV2 holds details about calls to the ListObjectsV2 method.
		ListObjectsV2 []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *s3.ListObjectsV2Input
			// OptFns is the optFns argument value.
			OptFns []func(*s3.Options)
		}
	}
	lockListObjectsV2 sync.RWMutex
}

// ListObjectsV2 calls ListObjectsV2Func.
func (mock *S3ClientMock) ListObjectsV2(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error) {
	if mock.ListObjectsV2Func == nil {
		panic("S3ClientMock.ListObjectsV2Func: method is nil but S3Client.ListObjectsV2 was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *s3.ListObjectsV2Input
		OptFns []func(*s3.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockListObjectsV2.Lock()
	mock.calls.ListObjectsV2 = append(mock.calls.ListObjectsV2, callInfo)
	mock.lockListObjectsV2.Unlock()
	return mock.ListObjectsV2Func(ctx, params, optFns...)
}

// ListObjectsV2Calls gets all the calls that were made to ListObjectsV2.
// Check the length with:
//
//	len(mockedS3Client.ListObjectsV2Calls())
func (mock *S3ClientMock) ListObjectsV2Calls() []struct {
	Ctx    context.Context
	Params *s3.ListObjectsV2Input
	OptFns []func(*s3.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *s3.ListObjectsV2Input
		OptFns []func(*s3.Options)
	}
	mock.lockListObjectsV2.RLock()
	calls = mock.calls.ListObjectsV2
	mock.lockListObjectsV2.RUnlock()
	return calls
}
